
version: '2.2'

services:

  starter_client:
    user: nobody
    image: cyberdojo/starter_client
    init: true
    container_name: test_starter_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - starter
    environment:
      - CYBER_DOJO_STARTER_SERVICE_NAME
      - CYBER_DOJO_STARTER_SERVICE_PORT
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_STARTER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_STARTER_CLIENT_PORT}:${CYBER_DOJO_STARTER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test_starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_START_POINTS_ROOT
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_STARTER_SERVICE_PORT}
    volumes:
      - ./server/start_points:${CYBER_DOJO_START_POINTS_ROOT}:ro

