
version: '2.2'

services:

  starter_client:
    user: nobody
    image: cyberdojo/starter_client
    init: true
    container_name: starter_client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - starter_server
    environment:
      - CYBER_DOJO_STARTER_SERVER_NAME
      - CYBER_DOJO_STARTER_SERVER_PORT
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: client
      args:
        - PORT=${CYBER_DOJO_STARTER_CLIENT_PORT}
    ports:
      - ${CYBER_DOJO_STARTER_CLIENT_PORT}:${CYBER_DOJO_STARTER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter_server:
    user: root
    image: cyberdojo/starter
    init: true
    container_name: starter_server
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    build:
      context: server
      args:
        - PORT=${CYBER_DOJO_STARTER_SERVER_PORT}
